WebsiteBanDoGiaDung/Controllers/ModuleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebsiteBanDoGiaDung.Models;

namespace WebsiteBanDoGiaDung.Controllers
{
    public class ModuleController : Controller
    {
        private WebsiteBanDoGiaDungDbContext db = new WebsiteBanDoGiaDungDbContext();
        // GET: Module
        public ActionResult Categories()
        {
            return View("_Categories", db.Categorys.Where(m=> m.Status == 1).ToList());
        }
        public ActionResult SlideShow()
        {
            // Position = 1 = SlideShow
            return View("_SlideShow", db.Sliders.Where(m => m.Status == 1 && m.Position == "1").ToList());
        }
        public ActionResult Header()
        {
            ViewBag.Promotion = db.Posts.Where(m => m.Status == 1 && m.Type == "post" && m.TopicID == 22).OrderByDescending(m => m.Created_at).Take(3).ToList();
            var list = db.Categorys.Where(m => m.Status == 1).ToList();
            return View("_Header", list);
        }
        public ActionResult Footer()
        {
            //ViewBag.Title = db.Menus.Where(m => m.Status == 1 && m.Positon == "footer" && m.ParentID == 0).Take(2).ToList();
            return View("_Footer", db.Menus.Where(m => m.Status == 1 && m.Positon == "footer").ToList());
        }
        public ActionResult HomeSlideShow()
        {
            ViewBag.Slider = db.Sliders.Where(m => m.Status == 1 && m.Position == "2").OrderByDescending(m => m.Created_at).Take(2).ToList();
            return View("_HomeSlideShow", db.Posts.Where(m => m.Status == 1 && m.Type == "post" && m.Position == "slider").ToList());
        }
        public ActionResult Popu()
        {
            return View("_Popu");
        }
        public ActionResult ListCategory()
        {
            var list = db.Categorys.Where(m => m.Status == 1 && m.ParentID == 0).ToList();
            return View("_ListCategory", list);
        }
        public ActionResult NewsHome()
        {
            return View("_NewsHome", db.Posts.Where(m => m.Status == 1 && m.Type == "post" && m.Position == "default").OrderByDescending(m => m.Created_at).Take(5).ToList());
        }
        public ActionResult Login()
        {
            return View("_Login");
        }
        public ActionResult MainMenu()
        {
            return View("_MainMenu", db.Menus.Where(m => m.Status == 1 && m.Positon == "header").ToList());
        }
        // partial page load with ajax
        public ActionResult MiTC()
        {
            return View("_MiTC");
        }
        public ActionResult ICart()
        {
            return View("_ICart");
        }
        public ActionResult ListPage()
        {
           
            return View("_ListPage", db.Posts.Where(m => m.Status == 1 && m.Type == "page").ToList());
        }
    }
}

WebsiteBanDoGiaDung/Views/Module/_Categories.cshtml
@model IEnumerable<WebsiteBanDoGiaDung.Models.MCategory>
<nav class="main-menu">
    <ul>
        @{int i = 1; }
        @foreach (var c in Model@*.Take(12)*@)
        {
            if (c.ParentID == 0)
            {
            <li>
                <a href="~/@c.Slug"><i class="nicon-@i"></i> &nbsp; @c.Name</a>
                <ul>
                    @foreach (var d in Model)
                    {
                        if (c.ID == d.ParentID)
                        {
                            <li>
                                <a href="~/@d.Slug" class="font-weight-bold">@d.Name</a>
                            </li>
                        }
                    }
                </ul>
            </li>
            }
            i++;
        }
    </ul>
</nav>

WebsiteBanDoGiaDung/Views/Module/_Footer.cshtml
@model IEnumerable<WebsiteBanDoGiaDung.Models.MMenu>

<style>
    .footer {
        border-top: 4px solid #ee4d2d;
        padding-top: 16px;
        background-color: #fff;
    }
    .footer__heading {
        font-size: 15px;
        text-transform: uppercase;
        color: rgba(0, 0, 0, 0.65);
        font-weight: 600;
        font-family: serif;
    }
    .footer-item__link {
        display: flex;
        align-items: center;
        text-decoration: none;
        color: rgba(0, 0, 0, 0.54);
        font-size: 13px;
        padding: 2px 0;
    }
        .footer-item__link:hover {
            color: red;
        }
    .footer-item__icon {
        font-size: 16.5px;
        margin-top: -1px;
        margin-right: 8px;
    }
    .footer_download-qr {
        width: 80px;
        height: 80px;
        object-fit: contain;
    }

    .footer_download-apps {
        margin-left: 16px;
    }

    .footer_download-app-img {
        height: 20px;
        margin-bottom: 2px;
    }
    .footer_download{
        display:flex;
    }
</style>
<footer class="footer">
    <div class="row container-91 my-4">
        <div class="col-2">
            <div class="footer__heading">VỀ CHÚNG TÔI</div>
            @foreach (var k in Model)
            {
                <a href="~/@k.Link" class="footer-item__link mt-1"> @k.Name</a>
            }
            <a href="" class="footer-item__link mt-1">Giới thiệu nhanam.vn</a>
            <a href="" class="footer-item__link mt-1">Điều khoản sử dụng</a>
            <a href="" class="footer-item__link mt-1">Điểm tích lũy </a>
        </div>

        <div class="col-3">
            <div class="footer__heading">CHĂM SÓC KHÁCH HÀNG</div>
            <a href="" class="footer-item__link mt-2">Trung tâm trợ giúp</a>
            <a href="" class="footer-item__link mt-1">Hướng dẫn mua hàng</a>
            <a href="" class="footer-item__link mt-1">Thanh toán</a>
            <a href="" class="footer-item__link mt-1">Trả tiền và hoàn tiền</a>
            <a href="" class="footer-item__link mt-1">Chính sách hỗ trợ</a>
        </div>
        <div class="col-3">
            <div class="footer__heading">THANH TOÁN</div>
            <a href="" class="footer-item__link mt-2">Thanh toán bằng tiền mặt</a>
            <a href="" class="footer-item__link mt-1">Thanh toán online</a>
        </div>
        <div class="col-md-2">
            <div class="footer__heading">THEO DÕI TRÊN</div>
            <a href="" class="footer-item__link mt-2">
                <i class="footer-item__icon fab fa-facebook"></i>
                Facebook
            </a>
            <a href="" class="footer-item__link mt-1">
                <i class="footer-item__icon fab fa-instagram"></i>
                Instagram
            </a>
            <a href="" class="footer-item__link mt-1">
                <i class="footer-item__icon fab fa-linkedin"></i>
                Linkedin
            </a>
        </div>
        <div class="col-md-2">
            <div class="footer__heading">Tải ứng dụng</div>
            <div class="footer_download">
                <img src="~/Public/img/qcode.png" alt="" class="footer_download-qr">
                <div class="footer_download-apps">
                    <a href="" class="footer_download-apps-link">
                        <img src="~/Public/img/appstore.png" alt="" class="footer_download-app-img">
                        <img src="~/Public/img/ggplay.png" alt="" class="footer_download-app-img">
                        <img src="~/Public/img/appkhac.png" alt="" class="footer_download-app-img">
                    </a>
                </div>
            </div>
        </div>

</footer>

WebsiteBanDoGiaDung/Views/Module/_Header.cshtml
@model IEnumerable<WebsiteBanDoGiaDung.Models.MCategory>
<style>
    ::placeholder{
        color:#000;
    }
</style>
<header>
    <div class="" style="background: #238b22; height: 30px; line-height: 30px; ">
        <div class="container-91 text-right">
            <small>
                @Html.Action("MainMenu", "Module")
            </small>
        </div>
    </div>
    <div class="wrapt">
        <div class="row container-91">
            <div class="col-sm-3 text-light float-left">
                <a href="/"
                   class="d-block text-decoration-none h3 text-center pt-2 text-white font-weight-bold">
                    &#128218; Nhanam.com
                </a>
            </div>
            <div class="col-sm-5 float-left">
                @using (Html.BeginForm("Search", "Site", FormMethod.Get, new { @class = "form-search-top" }))
                {
                    <input class="in-search text-primary" type="text" style="font-size: 14px;width:450px;" placeholder="Bạn cần tìm gì?..." name="key" value="@(Session["keywords"] ?? "")">
                    <button class="bt-search" type="submit"><i class="fas fa-search" style="color: #2196f3;"></i></button>
                }
            </div>
            <div class="col-sm-4 float-left pt-1">
                <div class="cart float-left pr-2" style="margin-top:-6px;margin-left:20px;">
                    <a href="~/gio-hang">
                        <button type="button" class="btn btn-cart">
                            <i class="fas fa-shopping-cart text-light"></i>
                            <small>
                                <span class="badge badge-light slc">
                                    @(Session["Cart"] != null ? ((List<WebsiteBanDoGiaDung.Library.ModelCart>)Session["Cart"]).Count() : 0)
                                </span>
                            </small>
                            <div style="font-size:11px; color:#d0efff">Giỏ hàng</div>
                        </button>
                    </a>
                    <div class="list-cart">
                        @if (Session["Cart"] != null)
                        {
                            <div class="t border-bottom">
                                Giỏ hàng của bạn
                            </div>
                            <ul class="container">
                                @{double Tong = 0;}
                                @foreach (var c in (List<WebsiteBanDoGiaDung.Library.ModelCart>)Session["Cart"])
                                {
                                    Tong += (c.Price * c.Quantity);
                                    <li>
                                        <div class="row my-3">
                                            <div class="col-4">
                                                <a href="~/@c.Slug">
                                                    <img src="~/Public/images/products/@c.Image" alt="@c.Name" width="70">
                                                </a>
                                            </div>
                                            <div class="col-7">
                                                <a href="~/@c.Slug" class="text-decoration-none">
                                                    <div class="name"> @c.Name</div>
                                                </a>
                                                <div class="price">
                                                    Đơn giá: @c.Price.ToString("N0") ₫
                                                </div>
                                                <div class="quantity">Số lượng: @c.Quantity</div>
                                            </div>

                                            <div class="col-1 p-0 m-0">
                                                <a href="javascript:void(0)" data-toggle="tooltip" data-placement="right" class="m-remove-one"
                                                   data-id="@c.ProductID" title="Xóa khỏi giỏ hàng"><i class="fas fa-times-circle"></i></a>
                                            </div>
                                        </div>

                                    </li>
                                }
                                <div class="row mb-3 mt-2 clearfix">
                                    <div class="col-7">
                                        Tổng: <strong class="float-right" style="color:#ee4d2d">
                                            @Tong.ToString("N0")₫
                                        </strong>
                                    </div>
                                    <div class="col-5">
                                        <div class="m-0 px-2 btn btn-primary btn-sm float-right">
                                            <a href="~/gio-hang" class="text-white text-decoration-none">
                                                Thanh toán
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </ul>
                        }
                        else
                        {
                            <div class="t">
                                <img src="~/Public/images/null.png" alt="Trống" width="100">
                                <div class="pb-5 font-weight-bold" style="opacity: .6;">
                                    Giỏ hàng của bạn trống
                                </div>
                            </div>
                        }
                    </div>
                </div>
                <div class="ml-3 float-left">
                    <a href="~/tin-tuc" class="text-white font-weight-bold text-decoration-none">Tin tức</a>
                    <div><a href="~/tin-tuc" style="font-size:13px; color:#d0efff">Tin khuyến mại</a></div>
                </div>
                <div class="pl-3 float-left">
                    @*<button type="button" class="button_login" data-toggle="modal" data-target=".bd-example-modal-lg"
                                data-whatever="" data-backdrop="static" data-keyboard="false">
                            Đăng nhập,
                        </button>

                        <button type="button" class="button_dangky" data-toggle="modal" data-target="#exampleModal" data-backdrop="static"
                                data-keyboard="false">
                            Đăng ký thành viên
                        </button>*@
                    @Html.Action("Login", "Module")
                </div>
            </div>
        </div>
    </div>

    <div class="wrapb">
        <div class="container-91">
            <div class="cate float-left p-0">
                <a href="" class="pl-4 font-weight-bold">
                    <i class="fas fa-bars"></i>
                    &nbsp; DANH MỤC
                </a>
    
                <nav class="main-menu" style="z-index:9999999">
                    <ul>
                        @{int i = 1; }
                        @foreach (var c in Model@*.Take(12)*@)
                        {
                            if (c.ParentID == 0)
                        {
                    <li>
                        <a href="~/@c.Slug"><i class="nicon-@i"></i> &nbsp; @c.Name</a>
                        <ul>
                            @foreach (var d in Model)
                            {
                                if (c.ID == d.ParentID)
                                {
                                    <li>
                                        <a href="~/@d.Slug" class="font-weight-bold">@d.Name</a>
                                    </li>
                                }
                            }
                        </ul>
                    </li>
                }
                i+=1;
            }
                    </ul>
                </nav>
            </div>
            <div class="">
               @foreach(var t in ViewBag.Promotion)
               {
                <div class="promo float-left"> <a href="@t.Slug" class="text-dark text-decoration-none">@t.Title</a> </div>
               }
               
            </div>
        </div>
    </div>
</header>

WebsiteBanDoGiaDung/Views/Module/_HomeSlideShow.cshtml
@model IEnumerable <WebsiteBanDoGiaDung.Models.MPost>
<div class="row clearfix container-91">
    <div class="col-sm-3 p-0 m-0">
        @Html.Action("Categories", "Module")
    </div>
    <div class="col-sm-7 slider">
        @Html.Action("SlideShow", "Module")
    </div>
    <div class="col-sm-2">
        <div class="exp-news">
            <div class="pl-2 py-2 border-bottom border-light">
                <div class="fb-like" data-href="https://www.facebook.com/nhanampublishing" data-width="" data-layout="button_count" data-action="like" data-size="small" data-share="true"></div>
    
            </div>
            <div class="title text-dark font-weight-bold">
                <a href="~/tin-tuc" class="text-dark text-decoration-none">CẬP NHẬT TIN TỨC MỚI NHẤT 24/7</a> <i class="fas fa-caret-right"></i>
            </div>
            
            @foreach (var u in Model)
            {
        <div class="des-exp">
           
            <a href="~/@u.Slug" class="text-danger text-decoration-none">

                @u.Title
            </a>
        </div>
            }
        <div class="mb-4"></div>
            @foreach (var t in ViewBag.Slider)
            {
                <div class="my-1 pl-2">
                    <a href="@t.Url" class="my-5"><img src="~/Public/images/sliders/@t.Image" alt="@t.Name"></a>
                </div>
            }
        </div>
    </div>
</div>

WebsiteBanDoGiaDung/Views/Module/_ICart.cshtml
<script src="~/Public/js/target.min.js"></script>
@using WebsiteBanDoGiaDung.Library
@if (Session["Cart"] == null)
{
    <div class="container checkout-cart">
        <img src="~/Public/images/null.png" alt="Giỏ hàng của bạn đang trống" class="d-block m-auto" width="250" />
        <p class="text-center font-weight-bold" style="opacity: .6;">Giỏ hàng của bạn trống</p>
        <div class="btn rounded-0 m-auto d-block" style="width:200px; background:#ee4d2d">
            <a href="/" class="text-light text-decoration-none">MUA NGAY</a>
        </div>
    </div>
}
else
{
    <div class="container checkout-cart">
        <div class="row">
            <div class="col-12 my-cart pl-5"><i class="fas fa-carrot text-success pr-2"></i> Giỏ hàng của bạn</div>
        </div>
        <div class="row title mt-3 mb-2">
            <div class="col-5 pl-5">
                <input class="form-check-input" type="checkbox" style="position: relative;">
                &nbsp;&nbsp; &nbsp;Sản phẩm
            </div>
            <div class="col-2 text-center">Đơn giá</div>
            <div class="col-2 text-center">Số lượng</div>
            <div class="col-2 text-center">Thành tiền</div>
            <div class="col-1 text-center">Thao tác</div>
        </div>

        @{double Tong = 0; int count = 0;}
        @foreach (var c in (List<ModelCart>)Session["Cart"])
        {
            count++;
            Tong += (c.Price * c.Quantity);
            <div class="row content border-right border-bottom border-left">
                <div class="col-5 pl-5">
                    <input class="form-check-input" type="checkbox" style="position: relative;">&nbsp;&nbsp; &nbsp;
                    <a href="~/@c.Slug" class="text-decoration-none text-dark">
                        <img src="~/Public/images/products/@c.Image" alt=" @c.Name" width="70">
                        &nbsp; &nbsp; @c.Name
                    </a>
                </div>
                <div class="col-2 text-center"> @c.Price.ToString("N0")₫</div>
                <div class="col-2 text-center">
                    <div class="btn rounded-0 dout update" data-id="@c.ProductID" data-options="minus">-</div>

                    <input type="number" class="rounded-0 border etd pl-3 bg-white" style="width:50px; height:34px;margin:-5px;outline:0;border: 0;text-align:center" value="@c.Quantity" min="1" data-id="@c.ProductID">

                    <div class="btn rounded-0 douc update" data-id="@c.ProductID" data-options="add">+</div>
                </div>

                <div class="col-2 text-center" style="color:#ee4d2d">
                    @((c.Price * c.Quantity).ToString("N0"))₫
                </div>
                <div class="col-1 text-center">
                    <a href="#" class="b-remove-one text-decoration-none update" data-id="@c.ProductID" data-options="remove">Xóa</a>
                </div>
            </div>
        }
        <div class="my-2">
            <a href="cart/removeall" class="text-right d-block text-decoration-none" style="font-size:15px">Xóa tất cả</a>
        </div>
        <div class="row fb-totalp bg-white container m-auto border fixed-bottom py-3">
            <div class="col-3 pl-5">
                <input class="form-check-input" type="checkbox" style="position: relative;">
                &nbsp;&nbsp; &nbsp;Chọn tất cả (@count)
            </div>

            <div class="col-6 text-center">
                <div class="float-right">
                    Tổng tiền hàng (@count sản phẩm): &nbsp;<strong class="d-inline" style="color:#ee4d2d;font-size: 27px;">@Tong.ToString("N0")₫</strong>
                </div>
            </div>
            <div class="col-3">

                <div class="btn text-center rounded-0 text-light">
                    <a href="#" class="checkAuth text-white text-decoration-none"> Thanh toán</a>
                </div>
            </div>
        </div>

    </div>
}

WebsiteBanDoGiaDung/Views/Module/_ListCategory.cshtml
@model IEnumerable<WebsiteBanDoGiaDung.Models.MCategory>
<style>
    .dfs {
        color: #4a90e2;
        font-size: 15px;
    }
</style>
@*<div id="accordion">
        <div class="py-1 rounded-top" style="box-shadow: 0 0 4px 0 rgba(0, 0, 0, 0.2);background: #206bc1;">
            <button class="btn w-100 h-100 btn-sm text-light text-left pl-3" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                DANH MỤC SẢN PHẨM
            </button>
        </div>
        <div id="collapseOne" class="collapse show" data-parent="#accordion">
            <div class="list-group rounded-0 rounded-bottom" style="box-shadow: 0 0 4px 0 rgba(0, 0, 0, 0.2);">
                @foreach (var cat in Model)
                {
                    <a href="~/@cat.Slug" class="list-group-item list-group-item-action pl-3 py-1@((HttpContext.Current.Request.Url.AbsolutePath == "/" + cat.Slug)?" active":"")"> <small>@cat.Name </small></a>
                }
            </div>
        </div>
    </div>*@

<div id="accordion">

    <div class="btn w-100 h-100 bg-white text-left pl-2 py-2 font-weight-bold pt-2 rounded-0" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne" style="font-size:13px;color:#333">
        DANH MỤC <i class="fa fa-plus fa-sm float-right pr-3 pt-1" style="font-size:10px"></i>
    </div>

    <div id="collapseOne" class="collapse show bg-white pb-2" data-parent="#accordion">

        @foreach (var cat in Model)
        {
        <a href="~/@cat.Slug" class="text-decoration-none d-block ml-3 mb-1">
            @if (HttpContext.Current.Request.Url.AbsolutePath == "/" + cat.Slug)
            {
                <i class="check-cat"></i>
                <div class="font-weight-bold dfs d-inline" style="color:#000"> @cat.Name</div>
            }
            else
            {
                <i class="ucheck-cat"></i>
                <div class="dfs  d-inline"> @cat.Name</div>
            }
        </a>
        }
    </div>

</div>

WebsiteBanDoGiaDung/Views/Module/_ListPage.cshtml
@model IEnumerable<WebsiteBanDoGiaDung.Models.MPost>

@foreach (var k in Model)
{
    <a href="~/@k.Slug" class="ll text-decoration-none text-dark"> ‣ @k.Title</a>
}    

WebsiteBanDoGiaDung/Views/Module/_MainMenu.cshtml
@model IEnumerable<WebsiteBanDoGiaDung.Models.MMenu>
@foreach (var t in Model)
{
    <a href="~/@t.Link" class="text-white text-decoration-none mr-3">@t.Name</a>
}

WebsiteBanDoGiaDung/Views/Module/_MiTC.cshtml
<script src="~/Public/js/target.min.js"></script>
@if (Session["Cart"] != null)
{
    <div class="t border-bottom">
        Giỏ hàng của bạn
    </div>
    <ul class="container">
        @{double Tong = 0;}
        @foreach (var c in (List<WebsiteBanDoGiaDung.Library.ModelCart>)Session["Cart"])
        {
            Tong += (c.Price * c.Quantity);
            <li>
                <div class="row my-3">
                    <div class="col-4">
                        <a href="~/@c.Slug">
                            <img src="~/Public/images/products/@c.Image" alt="@c.Name" width="70">
                        </a>
                    </div>
                    <div class="col-7">
                        <a href="~/@c.Slug" class="text-decoration-none">
                            <div class="name"> @c.Name</div>
                        </a>
                        <div class="price">
                            Đơn giá: @c.Price.ToString("N0") ₫
                        </div>
                        <div class="quantity">Số lượng: @c.Quantity</div>
                    </div>

                    <div class="col-1 p-0 m-0">
                        <a href="javascript:void(0)" data-toggle="tooltip" data-placement="right" class="m-remove-one"
                           data-id="@c.ProductID" title="Xóa khỏi giỏ hàng"><i class="fas fa-times-circle"></i></a>
                    </div>
                </div>

            </li>
        }
        <div class="row mb-3 mt-2 clearfix">
            <div class="col-7">
                Tổng: <strong class="float-right" style="color:#ee4d2d">
                    @Tong.ToString("N0")₫
                </strong>
            </div>
            <div class="col-5">
                <div class="m-0 px-2 btn btn-primary btn-sm float-right">
                    <a href="~/gio-hang" class="text-white text-decoration-none">
                        Thanh toán
                    </a>
                </div>
            </div>
        </div>
    </ul>
}
else
{
    <div class="t">
        <img src="~/Public/images/null.png" alt="Trống" width="100">
        <div class="pb-5 font-weight-bold" style="opacity: .6;">
            Giỏ hàng của bạn trống
        </div>
    </div>
}

WebsiteBanDoGiaDung/Views/Module/_NewsHome.cshtml
<div class="container-91 title">Tin mới trong ngày hôm nay!</div>
<div class="container-91 wrap clearfix">

    <div class="bu-left">
        <iframe width="600" height="380" src="https://www.youtube.com/embed/_x-wCnGq_PU" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    </div>
    <div class="bu-right">
        @foreach (var c in Model)
        {
            <div class="wrap-card clearfix">
                <a href="@c.Slug">
                    <div class="card-img">
                        <img src="/Public/images/post/@c.Image" alt="@c.Title" width="130">
                    </div>
                    <div class="card-body">
                        <p class="card-text d-inline-block text-truncate text-dark text-wrap" style="width:20rem; height:100% ;">
                            @c.Title
                        </p>                     
                    </div>
                </a>
            </div>
        }


        @*<div class="wrap-card clearfix">
                <a href="">
                    <div class="card-img">
                        <img src="~/Public/images/danh-gia-robot-hut-bui-mi-robot-vacuum-mop-11-665x320.jpg"
                             alt="Card image cap" width="130">
                    </div>
                    <div class="card-body">
                        <p class="card-text">
                            Đánh giá robot hút bụi Mi Robot Vacuum Mop -"Con sen" chính hiệu cho
                            cuộc sống tiện nghi
                        </p>
                    </div>
                </a>
            </div>
            <div class="wrap-card clearfix">
                <a href="">
                    <div class="card-img">
                        <img src="~/Public/images/danh-gia-robot-hut-bui-mi-robot-vacuum-mop-11-665x320.jpg"
                             alt="Card image cap" width="130">
                    </div>
                    <div class="card-body">
                        <p class="card-text">
                            Đánh giá robot hút bụi Mi Robot Vacuum Mop -"Con sen" chính hiệu cho
                            cuộc sống tiện nghi
                        </p>
                    </div>
                </a>
            </div>
            <div class="wrap-card clearfix">
                <a href="">
                    <div class="card-img">
                        <img src="~/Public/images/danh-gia-robot-hut-bui-mi-robot-vacuum-mop-11-665x320.jpg"
                             alt="Card image cap" width="130">
                    </div>
                    <div class="card-body">
                        <p class="card-text">
                            Đánh giá robot hút bụi Mi Robot Vacuum Mop -"Con sen" chính hiệu cho
                            cuộc sống tiện nghi
                        </p>
                    </div>
                </a>
            </div>
            <div class="wrap-card clearfix">
                <a href="">
                    <div class="card-img">
                        <img src="~/Public/images/danh-gia-robot-hut-bui-mi-robot-vacuum-mop-11-665x320.jpg"
                             alt="Card image cap" width="130">
                    </div>
                    <div class="card-body">
                        <p class="card-text">
                            Đánh giá robot hút bụi Mi Robot Vacuum Mop -"Con sen" chính hiệu cho
                            cuộc sống tiện nghi
                        </p>
                    </div>
                </a>
            </div>
        <div class="wrap-card clearfix">
            <a href="">
                <div class="card-img">
                    <img src="~/Public/images/danh-gia-robot-hut-bui-mi-robot-vacuum-mop-11-665x320.jpg"
                         alt="Card image cap" width="130">
                </div>
                <div class="card-body">
                    <p class="card-text">
                        Đánh giá robot hút bụi Mi Robot Vacuum Mop -"Con sen" chính hiệu cho
                        cuộc sống tiện nghi
                    </p>
                </div>
            </a>
        </div>*@
    </div>
</div>

WebsiteBanDoGiaDung/Views/Module/_Popu.cshtml
<div style="background-color:#f3f3f3;" class="py-2">
    <div class="container-91">
        <a href=""><img src="images/banners/03-1200x140.jpg" alt="" width="100%"></a>
    </div>
</div>
<div style="background-color:#f3f3f3;" class="py-2">
    <div class="container-91 bg-white py-2 px-3">
        Tìm kiếm nhiều:
        <a class="pl-3" href="">Truyện tranh</a>
        <a class="pl-3" href="">Thuật giả kim</a>
        <a class="pl-3" href="">Văn học Việt Nam</a>
        <a class="pl-3" href="">Dạy con làm giàu</a>
        <a class="pl-3" href="">Khoa học- Công nghệ</a>
        <a class="pl-3" href="">Phong cách giao tiếp</a>
    </div>
</div>